Release
silinternational/wecarry-terraform pull request #18
Opened 2020-01-29 20:22 UTC by Schparky

- Office 365 variables (#14 )
- Service integration token (#15)
- Lambda credentials (#16)

2020-01-29 20:24 UTC, Baggerone approved these changes

2020-01-30 22:53 UTC, fillup requested changes

2020-01-30 22:53 UTC, fillup commented on task-def-api.json
> +    },
Error?

2020-01-30 22:53 UTC, fillup commented on task-def-api.json
> +    },
Error?

2020-02-03 19:57 UTC, Baggerone reviewed
I'll leave it to Phillip to approve this.

2020-02-03 20:25 UTC, fillup approved these changes

2020-02-03 20:30 UTC, merged